name: Bravo Portfolio
favicon: null
layout_spectrum: 0.50344
typography_spectrum: 0.6410727011971176
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#141414'
    - '#363636'
    - '#9d9d9d'
    - '#c9c9c9'
  brandStrength: 0
  lightness: 0.625
  saturation: 1
  rhythmicContrast: 0
purpose: []
